//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.19 at 02:25:38 PM EST 
//


package com.fmo.wom.domain;

import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.fmo.wom.helper.XmlListAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fmo.wom.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * @param <T>
 * 
 */
@XmlRegistry
public class ObjectFactory<T> {

    private final static QName _OrderBO_QNAME = new QName("", "OrderBO");
    private final static QName _GetShipment_QNAME = new QName("", "GetShipment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fmo.wom.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreditCardBO }
     * 
     */
    public CreditCardBO createCreditCardBO() {
        return new CreditCardBO();
    }

    /**
     * Create an instance of {@link AddressBO }
     * 
     */
    public AddressBO createAddressBO() {
        return new AddressBO();
    }

    /**
     * Create an instance of {@link TradingPartnerBO }
     * 
     */
    public TradingPartnerBO createTradingPartnerBO() {
        return new TradingPartnerBO();
    }

    /**
     * Create an instance of {@link DistributionCenterBO }
     * 
     */
    public DistributionCenterBO createDistributionCenterBO() {
        return new DistributionCenterBO();
    }

    /**
     * Create an instance of {@link CountryBO }
     * 
     */
    public CountryBO createCountryBO() {
        return new CountryBO();
    }

    /**
     * Create an instance of {@link WomCodeDescBO }
     * 
     */
//    public WomCodeDescBO createWomCodeDescBO() {
//        return new WomCodeDescBO();
//    }

    /**
     * Create an instance of {@link AccountBO }
     * 
     */
    public AccountBO createBillToAcctBO() {
        return new AccountBO();
    }

    /**
     * Create an instance of {@link ShippingMethodBO }
     * 
     */
    public ShippingMethodBO createShippingMethodBO() {
        return new ShippingMethodBO();
    }

    /**
     * Create an instance of {@link PriceBO }
     * 
     */
    public PriceBO createPriceBO() {
        return new PriceBO();
    }

    /**
     * Create an instance of {@link ShippingUnitBO }
     * 
     */
    public ShippingUnitBO createShippingUnitBO() {
        return new ShippingUnitBO();
    }

    /**
     * Create an instance of {@link ExternalSystemBO }
     * 
     */
    public ExternalSystemBO createExternalSystemBO() {
        return new ExternalSystemBO();
    }

    /**
     * Create an instance of {@link WeightBO }
     * 
     */
    public WeightBO createWeightBO() {
        return new WeightBO();
    }

    /**
     * Create an instance of {@link CurrencyTypeBO }
     * 
     */
    public CurrencyTypeBO createCurrencyTypeBO() {
        return new CurrencyTypeBO();
    }

    /**
     * Create an instance of {@link ComponentBO }
     * 
     */
    public ComponentBO createComponentBO() {
        return new ComponentBO();
    }

    /**
     * Create an instance of {@link KitBO }
     * 
     */
    public KitBO createKitBO() {
        return new KitBO();
    }

    /**
     * Create an instance of {@link ItemBO }
     * 
     */
    public ItemBO createItemBO() {
        return new ItemBO();
    }

    /**
     * Create an instance of {@link InventoryBO }
     * 
     */
    public InventoryBO createInventoryBO() {
        return new InventoryBO();
    }

    /**
     * Create an instance of {@link QuantityBO }
     * 
     */
    public QuantityBO createQuantityBO() {
        return new QuantityBO();
    }

    /**
     * Create an instance of {@link UnitOfMeasureBO }
     * 
     */
    public UnitOfMeasureBO createUnitOfMeasureBO() {
        return new UnitOfMeasureBO();
    }

    /**
     * Create an instance of {@link OrderBO }
     * 
     */
    public OrderBO createOrderBO() {
        return new OrderBO();
    }

    /**
     * Create an instance of {@link PartBO }
     * 
     */
    public PartBO createPartBO() {
        return new PartBO();
    }

    /**
     * Create an instance of {@link SapAcctBO }
     * 
     */
    public SapAcctBO createSapAcctBO() {
        return new SapAcctBO();
    }

    /**
     * Create an instance of {@link KitTypeBO }
     * 
     */
    public KitTypeBO createKitTypeBO() {
        return new KitTypeBO();
    }

    /**
     * Create an instance of {@link ShipToAcctBO }
     * 
     */
    public ShipToAcctBO createShipToAcctBO() {
        return new ShipToAcctBO();
    }

    /**
     * Create an instance of {@link AccountBO }
     * 
     */
    public AccountBO createAccountBO() {
        return new AccountBO();
    }

    /**
     * Create an instance of {@link ProblemBO.CorrectiveOptions }
     * 
     */
//    public ProblemBO.CorrectiveOptions createProblemBOCorrectiveOptions() {
//        return new ProblemBO.CorrectiveOptions();
//    }

    /**
     * Create an instance of {@link WomBaseBO }
     * 
     */
//    public WomBaseBO createWomBaseBO() {
//        return new WomBaseBO();
//    }

    /**
     * Create an instance of {@link ProblemBO }
     * 
     */
    public ProblemBO createProblemBO() {
        return new ProblemBO();
    }

    /**
     * Create an instance of {@link ProblemBO.CorrectiveOptions.Entry }
     * 
     */
//    public ProblemBO.CorrectiveOptions.Entry createProblemBOCorrectiveOptionsEntry() {
//        return new ProblemBO.CorrectiveOptions.Entry();
//    }

    /**
     * Create an instance of {@link SalesChannelBO }
     * 
     */
    public SalesChannelBO createSalesChannelBO() {
        return new SalesChannelBO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrderBO")
    public JAXBElement<OrderBO> createOrderBO(OrderBO value) {
        return new JAXBElement<OrderBO>(_OrderBO_QNAME, OrderBO.class, null, value);
    }
    @XmlElementDecl(namespace = "", name = "GetShipment")
    public JAXBElement<Object> createGetShipment() {
    	return new JAXBElement<Object>(_GetShipment_QNAME, Object.class, null,null);
    }
    public XmlListAdapter<T> createXmlListAdapter(List<T> value) {
        return new XmlListAdapter<T>(value);
    }
    public ShippedOrderBO createShippedOrderBO() {
        return new ShippedOrderBO();
    }
    

}
