
package com.fmo.wom.iposervice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This web service is a template for the standard AAIA IPO (Internet Parts Ordering) Web Service.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InternetPartsOrderWebService", targetNamespace = "http://www.aaiasoa.org/IPOv2", wsdlLocation = "file:/D:/KeshavBKP/IPOWorkspace/TestWOMServicesWeb/WebContent/WEB-INF/wsdl/ipo201/InternetPartsOrder.wsdl")
public class InternetPartsOrderWebService
    extends Service
{

    private final static URL INTERNETPARTSORDERWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTERNETPARTSORDERWEBSERVICE_EXCEPTION;
    private final static QName INTERNETPARTSORDERWEBSERVICE_QNAME = new QName("http://www.aaiasoa.org/IPOv2", "InternetPartsOrderWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/KeshavBKP/IPOWorkspace/TestWOMServicesWeb/WebContent/WEB-INF/wsdl/ipo201/InternetPartsOrder.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTERNETPARTSORDERWEBSERVICE_WSDL_LOCATION = url;
        INTERNETPARTSORDERWEBSERVICE_EXCEPTION = e;
    }

    public InternetPartsOrderWebService() {
        super(__getWsdlLocation(), INTERNETPARTSORDERWEBSERVICE_QNAME);
    }

    public InternetPartsOrderWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTERNETPARTSORDERWEBSERVICE_QNAME, features);
    }

    public InternetPartsOrderWebService(URL wsdlLocation) {
        super(wsdlLocation, INTERNETPARTSORDERWEBSERVICE_QNAME);
    }

    public InternetPartsOrderWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTERNETPARTSORDERWEBSERVICE_QNAME, features);
    }

    public InternetPartsOrderWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InternetPartsOrderWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InternetPartsOrderWebServiceSoap
     */
    @WebEndpoint(name = "InternetPartsOrderWebServiceSoap")
    public InternetPartsOrderWebServiceSoap getInternetPartsOrderWebServiceSoap() {
        return super.getPort(new QName("http://www.aaiasoa.org/IPOv2", "InternetPartsOrderWebServiceSoap"), InternetPartsOrderWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InternetPartsOrderWebServiceSoap
     */
    @WebEndpoint(name = "InternetPartsOrderWebServiceSoap")
    public InternetPartsOrderWebServiceSoap getInternetPartsOrderWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aaiasoa.org/IPOv2", "InternetPartsOrderWebServiceSoap"), InternetPartsOrderWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTERNETPARTSORDERWEBSERVICE_EXCEPTION!= null) {
            throw INTERNETPARTSORDERWEBSERVICE_EXCEPTION;
        }
        return INTERNETPARTSORDERWEBSERVICE_WSDL_LOCATION;
    }

}
